node{
    // Script for Ubuntu machine

	def mavenHome = tool name: 'maven-3', type: 'maven'
	def mavenCMD = "${mavenHome}/bin/mvn"
	
	def dockerHome = tool name: 'docker', type: 'dockerTool'
	def dockerCMD = "${dockerHome}/bin/docker"

	stage('git checkout'){
		// code for checkout
		git 'https://github.com/suvradipdutta/devops-bootcamp.git'
	}
	
	stage('mvn version'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} --version"
	    }
	}	
	
	stage('mvn clean'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} clean"
	    }
	}
	
	stage('mvn compile'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} compile"
	    }
	}	
	
	stage('mvn test'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} test"
	    }
	}	
	
	stage('mvn package'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} package"
	    }
	}		
	    
	stage('self checks') {
        dir("cicd-pipeline/target") {
            sh "ls -lrt *.jar"
		}
	}
	
	stage('docker version') {
		sh "${dockerCMD} --version"
	}
	
	stage('docker build') {
        dir("cicd-pipeline") {
            sh "${dockerCMD} build -t suvradipdutta/springboot_app:1.1.${env.BUILD_NUMBER} ."
		}
	}

	stage('docker login') {
		withCredentials([string(credentialsId: 'dockerHub', variable: 'dockerPassword')]) {
			sh "${dockerCMD} login -u suvradipdutta -p ${dockerPassword}"
		}
	}
	
	stage('docker push') {
		sh "${dockerCMD} push suvradipdutta/springboot_app:1.1.${env.BUILD_NUMBER}"
	}

	stage('docker kill') {
		sh "docker ps --filter publish=8100 --format {{.ID}} > container_id.file"
		try{
			sh "docker kill ${cat container_id.file}"
		} catch (Exception e) {
			echo "No running containers to kill"
		}
	}

	stage('docker run') {
		sh "${dockerCMD} run -p 8888:8100 -d suvradipdutta/springboot_app:1.1.${env.BUILD_NUMBER}"
	}
	
	stage('cleanup workspace') {
         cleanWs()
	}	

}