node{
    // Script for Ubuntu machine
    
    def mavenHome = tool name: 'maven-3', type: 'maven'
	def mavenCMD = "${mavenHome}/bin/mvn"
	
	def dockerHome = tool name: 'docker', type: 'dockerTool'
	def dockerCMD = "${dockerHome}/bin/docker"

	stage('git checkout'){
		// code for checkout
		git 'https://github.com/suvradipdutta/devops-bootcamp.git'
	}
	
	stage('mvn clean'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} clean"
	    }
	}
	
	stage('mvn compile'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} compile"
	    }
	}	
	
	stage('mvn test'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} test"
	    }
	}	
	
	stage('mvn package'){
		// code for build
        dir("cicd-pipeline") {
		    sh "${mavenCMD} package"
	    }
	}		
	    
	stage('Self checks') {
        dir("cicd-pipeline/target") {
            sh "ls -lrt"
        }
	}
	
	stage('Docker checks') {
        dir("cicd-pipeline/target") {
            sh "{dockerCMD} --version"
        }
	}

}